var subjectObject = {

    "Kachin": {
        "Myitkyina": ["Myitkyina", "Aungmyintha", "Sitapu"],
        "Naungmon": ["Naungmon", "Pannandin", "Khareng"],
        "Bhamaw": ["Bhamaw", "Sinthay"],
        "Chibwe": ["Chibwe", "Panwar", "Chipyit"],
        "Ingyanyan": ["Ingyanyan", "Hkawan"],
        "Khaunglanphu": ["Khaunglanphu", "Tangbau"],
        "Machanbaw": ["Machanbaw", "Zarbung"],
        "Mansi": ["Mansi", "Manwingyi"],
        "Mogaung": ["Mogaung", "Nmtee", "Pinbaw", "Mongyang"],
        "Mohnyin": ["Mohnyin", "Hopin", "Mawhan", "Nantmon", "Mongmao"],
        "Momauk": ["Momauk", "Myothit", "Namhkam"],
        "Phakant": ["Phakant", "Karmine", "Hkamti"],
        "Putao": ["Putao", "Kaunghe"],
        "Sawlaw": ["Sawlaw", "Kawmun"],
        "Shwegu": ["Shwegu", "Sinkham", "Mandalin"],
        "Sinbo": ["Sinbo", "Zayangyi"],
        "Sunpayabom": ["Sunpayabom", "Yangyang"],
        "Taning": ["Taning", "Htamanthi"],
        "Waingmaw": ["Waingmaw", "Warshaung", "Lajayang"]
    },


    "Kayah": {
        "Bawlakhe": ["Bawlakhe", "Ywa Thit"],
        "Demohso": ["Demohso", "Dawtamagyi"],
        "Loikaw": ["Loikaw", "Lawpita", "Loilenlay"],
        "Meisei": ["Meisei"],
        "Pharuso": ["Pharuso"],
        "Phasaung": ["Phasaung", "Mawchee"],
        "Shartaw": ["Shartaw"]
    },


    "Kayin": {
        "Hlainebwe": ["Hlainebwe", "Paingkyon", "Shwegwan"],
        "Hpaan": ["Hpaan", "Barkat", "Htonaing", "Myaingkalay", "Zarthapyin"],
        "Hpapun": ["Hpapun", "Kamamaung"],
        "Kawkareit": ["Kawkareit", "Kyondo"],
        "Kyarinseikkyi": ["Kyarinseikkyi", "Kyaikdon"],
        "Myawaddy": ["Myawaddy", "ThinkhabNyinaung"],
        "Thantaunggyi": ["Thantaunggyi", "Thantaungthit", "Latetho"]
    },

    "Chin": {
        "Falam": ["Falam", "Reed", "Loneban"],
        "Hakah": ["Hakah", "Su-Khua", "Khonekyone"],
        "Htantalan": ["Htantalan", "Thikee", "Faroom"],
        "Kanpetlat": ["Kanpetlat", "Shinbaung"],
        "Matupi": ["Matupi", "Rezwa", "Oakka", "Lailanpi"],
        "Mindat": ["Mindat", "Aukchang"],
        "Teetain": ["Teetain", "Htotehlaing", "Tweehtan", "Saizang", "Tunzan", "Kyeekhar"]
    },

    "Mon": {
        "Beelin": ["Beelin", "Taungzon"],
        "Chaungsone": ["Chaungsone", "Kalwi", "Muyitkalay", "Ywalut"],
        "Kyaikhto": ["Kyaikhto", "Theinzayet", "Kyeikhteeyoyinpyin", "Kyeikkatha", "Mayangone", "Mokepalin", "Sittaung"],
        "Kyaikmaraw": ["Kyaikmaraw", "Nyaungbinseik", "Chaungnagwa", "Tayanar"],
        "Mawlamyaing": ["Mawlamyaing", "Daingwunkwin", "Daweizu", "Kadoe", "Mawlamyaing University", "Mupon", "Myaingthaya", "Zayyathiri"],
        "Mudon": ["Mudon", "Hpaout", "Kaloutthaut", "Kamawet", "Nattaung"],
        "Paung": ["Paung", "Ahhlat", "Kywechan", "Mottama", "Yinnyein", "Zinkyeik"],
        "Thahton": ["Thahton", "Theinseik", "Thutdamawaddy"],
        "Thanbyuzayet": ["Thanpyuzayet", "Kyonkadat", "Panga", "Wegali", "Kyaikkhame"],
        "Ye": ["Ye", "Ahsin", "Hnitkayin", "Khawza", "Kyaungywa", "Lamine"]
    },


    "Rakhine": {
        "Ann": ["Ann", "Tattaung"],
        "Buthidaung": ["Buthidaung", "Ponnyolate", "Kahtila", "Nyanugchaung"],
        "Gwa": ["Gwa", "Kyeintail", "Kanthaya"],
        "Kyaukphyu": ["Kyaukphyu", "Zinchaung", "Apaukwa"],
        "Mamaung": ["Mamaung", "Thitpon"],
        "Maungdaw": ["Maungdaw", "Aungthapyay", "Kyaukpantu", "Mingalarnyunt"],
        "Minbya": ["Minbya", "Kanni"],
        "MyaukOo": ["MyaukOo", "Myaungbwe"],
        "Myepon": ["Myepon"],
        "Paletwa": ["Paletwa"],
        "Panmyaung": ["Panmyaung"],
        "Pauktaw": ["Pauktaw"],
        "Ponnagyun": ["Ponnagyun", "Thetat"],
        "Rambree": ["Rambree", "Kyauknimaw"],
        "Rathedaung": ["Rathedaung", "Ahngumaw"],
        "Sittwe": ["Sittwe", "Mingan", "Thatkaypyin"],
        "Taunggoke": ["Taunggoke", "Ywama", "Lamu"],
        "Thandway": ["Ngapali", "Kinmaw", "Pazunphay", "Thandway"]
    },

    "Shan": {
        "Chinshwehaw": ["Chinshwehaw"],
        "Homain": ["Homain"],
        "Hopan": ["Hopan", "Minepauk", "Mineyang"],
        "Hopone": ["Hotaung", "Nanttit", "Seloo"],
        "Inndaw": ["Panlone"],
        "Kalaw": ["Hopone", "Mankyeepin", "Minewa", "Mineyaung", "Mineyel"],
        "Karli": ["Kyaukkacha"],
        "Khollan": ["Kyauktan"],
        "Khonegyan": ["Inndaw"],
        "Konhein": ["Aungpan", "Moemate"],
        "Konlon": ["Bawsai"],
        "Kutkai": ["Heho", "Manheiro", "Moenae", "Monekoe"],
        "Kyainglatt": ["Kalaw", "Muse"],
        "Kyaingtaung": ["Myindike"],
        "Kyaingtong": ["Monewee", "Sellan", "Wetpyuyae"],
        "Kyaukme": ["Karli", "Kyarsakhan", "Maingyin", "Nankham"],
        "Kyauktalone": ["Khollan"],
        "Kyaythee": ["khonegyan", "Mansan"],
        "Lashio": ["Bawtwin", "Manaung", "Mineseike", "Tarkaw"],
        "Laukkaing": ["Konlon"],
        "Linkhe": ["Kaungkhar"],
        "Loilin": ["Kangyi", "Kutkai"],
        "Mabain": ["Manpyain"],
        "Manton": ["Nantphatka"],
        "Maukmai": ["Mainglone", "Tamoehnye"],
        "Minekai": ["Kyainglatt", "Wanpon"],
        "Minelar": ["Kyaingtong", "Minelar"],
        "Minemaw": ["Loimwe"],
        "Minekhote": ["Kyaingtong"],
        "Mineyaung": ["Kyainglatt", "Khaungtaing", "Kyaysargone", "Lashio"],
        "Mineyel": ["Lashiogyi", "Maingyaw"],
        "Mineyu": ["Mineyu"],
        "Moemate": ["Mansanyaekya"],
        "Muse": ["Minethouk", "Nanpan", "Nantpaung", "Ngaphe'chaung"],
        "Namhpai": ["Mabain"],
        "Nankham": ["Naungmon", "Sagar"],
        "Nansang": ["Minepon"],
        "Nantmatu": ["Linkhe", "Panwine"],
        "Nantsan": ["Kharatdon"],
        "Naungcho": ["Moebywe", "Phiekon", "Pinlaung", "Pinlone University", "Shwepyiaye"],
        "Nyaungshwe": ["Banyin", "Kyone", "Maukmai", "Naungmon", "Pitaya", "Pwayhla", "Saikehaung", "Tikyit"],
        "Taunggyi": ["Nantlan", "Pinphit", "Sinkyawt", "Taungni", "Thipaw", "Tonta"],
        "Thipal": ["Bahtoo", "Minesatt", "Mineshue"],
        "Yatsauk": ["Kaungbo", "Wantkan"],
        "Ywarngan": ["Myinkyadoe", "YeiOo", "Ywarngan"]
    },

    "Tanintharyi": {
        "Bokpyin": ["Bokpyin", "Pyigyimandaing"],
        "Dawei": ["Dawei", "Myittha"],
        "Kawthaung": ["Kawthaung"],
        "Kyunzu": ["Kyunzu"],
        "Launglone": ["Launglone", "Maungmagun", "Thakyettaw"],
        "Myeik": ["Myeik"],
        "Palaw": ["Palaw"],
        "Tanintharyi": ["Tanintharyi"],
        "Thayetchaung": ["Thayetchaung"],
        "Yephyu": ["Yephyu", "Pagawzun", "Kanbauk"]
    },

    "Sagaing": {
        "Ahyadaw": ["Ahyadaw"],
        "Banmauk": ["Banmauk"],
        "Budalin": ["Budalin"],
        "Chaung U": ["Chaung U"],
        "Depeyin": ["Depeyin"],
        "Homalin": ["Homalin"],
        "Indaw": ["Indaw", "Meza"],
        "Kale": ["Kale", "Natchaung"],
        "Kalewa": ["Kalewa"],
        "Kani": ["Kani"],
        "Kantbalu": ["Kantbalu", "Chatthin", "Htantabin", "HtanKone"],
        "Katha": ["Katha", "Inywa"],
        "Kawlin": ["Kawlin", "Koehtaungbo"],
        "Kantee": ["Kantee"],
        "Khin U": ["Khin U"],
        "Kyunhla": ["Kyunhla"],
        "Laheir": ["Laheir"],
        "Layshee": ["Layshee"],
        "Mawlaik": ["Mawlaik"],
        "Mingin": ["Mingin"],
        "Monywa": ["Monywa", "Thazi"],
        "Myaung": ["Myanug"],
        "Myinmu": ["Myinmu"],
        "Nanyun": ["Nanyun"],
        "Pale": ["Pale"],
        "Phaungpyin": ["Phaungpyin"],
        "Pinlebu": ["Pinlebu"],
        "Sagaing": ["Sagaing", "Nyaungpinwine", "Ywathitgyi"],
        "Sarlingyi": ["Sarlingyi"],
        "Shwebo": ["Shwebo", "Kyaukmyaung"],
        "Tamu": ["Tamu"],
        "Taze": ["Taze"],
        "Tigyaing": ["Tigyaing"],
        "Wetlet": ["Wetlet"],
        "Wuntho": ["Wuntho", "Nankhan"],
        "YeU": ["YeU"],
        "Yinmabin": ["Yinmabin"]
    },


    "Ayeyarwady": {
        "Bogalay": ["Bogalay"],
        "Ahmar": ["Ahmar"],
        "Danubyu": ["Danubyu"],
        "Dedaye": ["Dedaye", "Suukalap"],
        "Einme": ["Einme"],
        "Hainggyi": ["Hainggyi", "Kyonekuu"],
        "Hinthada": ["Hinthada", "Nateban", "Hinthadauniversity", "Yonethalin"],
        "Ingabu": ["Ingabu", "Kwingauk", "Mezalegine", "Nyaungkyo", "Zaungtan"],
        "Kangyidaung": ["Kangyidaung", "Kanywa"],
        "Kyaiklat": ["Kyaiklat", "Yonedaunt"],
        "Kyankhin": ["Kyankhin"],
        "Kyaunggone": ["Kyaunggone"],
        "Kyonepyaw": ["Kyonepyaw", "Thaungyi"],
        "Labutta": ["Labutta", "Kyarkan", "Kanbat"],
        "Laymyethar": ["Laymyethar", "Khamoutsu"],
        "Maubin": ["Maubin", "Shwetaunghmaw", "Sitchaung", "Yeelaekalay"],
        "Mawlamyainggyun": ["Mawlamyainggyun", "Hlaingbone"],
        "Myanaung": ["Myanaung", "Innbin", "Kanaung", "Ngapiseik", "Shwekyin"],
        "Myaungmya": ["Myaungmya", "Sagarmyar", "Yetwinyekan"],
        "Ngaputaw": ["Ngaputaw"],
        "Ngathaingchaung": ["Ngathaingchaung", "Ngathaingchaung"],
        "Ngwesaung": ["Ngwesaung", "Sinma"],
        "Nyaungtone": ["Nyaungtone", "Sarmalout"],
        "Pantanaw": ["Pantanaw"],
        "Pathein": ["BED", "GCC", "GTC", "Kyitha", "Myetto", "Pathein", "Patheinuniversity"],
        "Pyapon": ["Kyitha", "Kyonekadon", "Thaminhtaw", "Pyapon"],
        "Pyinsalu": ["Pyinsalu"],
        "Shwethaungyan": ["Shwethaungyan", "Chaungtha"],
        "Thabaung": ["Thabaung"],
        "Kyamange": ["Wakema"],
        "Kyungone": ["Warkema"],
        "Shwelaung": ["Warkema"],
        "Ahthoke": ["Yegyi"],
        "Ngapiseik": ["Yegyie"],
        "Thidakonpyin": ["Yegyi"],
        "Yodayartet": ["Yegyie"],
        "Zaythala": ["Yegyi"],
        "Zalun": ["Zalun"]
    },


    "Naypyitaw": {
        "Detkhinathiri": ["Detkhinathiri"],
        "Lewe": ["Lewe", "Alar", "Tharwuthti", "Thekawgyi"],
        "Oketarathiri": ["Oketarathiri"],
        "Pokebathiri": ["Pokebathiri"],
        "Pyinmana": ["Pyinmana", "Pyinmana (MyoHaung)"],
        "Shwemyoe": ["Tatkone"],
        "Tatkone": ["Tatkone"],
        "Zayyarthiri": ["Zayyarthiri"]
    },

    "Mandalay": {
        "Mandalay": ["Chanmyathazi", "Chanayethazan", "Amarapura", "Yadanarponuniversity"],
        "Kyaukpadaung": ["Kyaukpadaung", "Popa"],
        "Kyaukse": ["Kyaukse", "Thanywa"],
        "Madaya": ["Madaya"],
        "Mahaaungmyae": ["Mandalayuniversity"],
        "Mahlaing": ["Mahlaing"],
        "Meikhtila": ["Meikhtila"],
        "Myingyan": ["Myingyan", "Myingyanmyoma"],
        "Myitthar": ["Myitthar"],
        "Nahtoegyi": ["Nahtoegyi"],
        "Ngazune": ["Ngazune"],
        "Nyaungoo": ["Nyaungoo", "Bagan", "Singu"],
        "Patheingyi": ["MTU", "Patheingyihtonbo", "Patheingyi"],
        "Pyawbwe": ["Pyawbwe", "Yanaung"],
        "Pyaygyidakhon": ["Pyaygyidakhon", "Sathmutmyothit"],
        "Pyinoolwin": ["Pyinoolwin", "CSTC", "Padaythamyothit"],
        "Sintgu": ["Latpanhla", "Htonegyi", "Sintgu"],
        "Sintkaing": ["Sintkaing"],
        "Tadau": ["Tadau"],
        "Taungtha": ["Taungtha", "Semakan", "Welaung", "Ywathit"],
        "Thabeikkyin": ["Thabeikkyin"],
        "Tharzi": ["Tharzi", "Hanza", "Nyaungyan"],
        "Wundwin": ["Wundwin", "Thedaw"],
        "Yamethin": ["Theinkonegyi", "Yamethin"]
    },


    "Bago": {
        "Bago": ["Bago", "Oakthamyothit", "Tarwayedagar", "Thayaaye"],
        "Deiku": ["Ayethukha", "Phaungdawthi"],
        "Gyobingauk": ["Gyobingauk"],
        "Htantabin": ["Htantabin", "Zayatgyi"],
        "Kawa": ["Kawa"],
        "Kyaukgyi": ["Kyaukgyi"],
        "Kyauktagar": ["Kyauktagar"],
        "Letpadan": ["Letpadan"],
        "Minhla": ["Minhla"],
        "Moenyo": ["Moenyo"],
        "Nattalin": ["Nattalin"],
        "Nyaunglaybin": ["Nyaunglaybin"],
        "Oakpho": ["Oakpho"],
        "Oaktwin": ["Oaktwin"],
        "Padaung": ["Padaung", "Htonebo"],
        "Pandaung": ["Thuyetan"],
        "Paukkhaung": ["Paukkhang"],
        "Phyu": ["Phyu"],
        "Pyay": ["Pyay"],
        "Shwedaung": ["Shwedaung"],
        "Shwekyin": ["Shwekyin"],
        "Taungoo": ["Taungoo", "Kaytumadi"],
        "Thanapin": ["Thanapin", "Kyungyi"],
        "Tharrawaddy": ["Tharrawaddy"],
        "Thegone": ["Thegone"],
        "Waw": ["Waw"],
        "Yedashe": ["Yedashe", "Swa", "Yeni"],
        "Zeegon": ["Zeegon"]
    },

    "Magwe": {
        "Aunglan": ["Aunglan", "Kyawswa"],
        "Chauk": ["Chauk"],
        "Gantgaw": ["Gantgaw", "Minywa"],
        "Htilinn": ["Htilinn"],
        "Kanma": ["Kanma", "Yenantha"],
        "Magwe": ["Magwe", "Yanpae"],
        "Minbu": ["Minbu"],
        "Mindonn": ["Mindonn", "Minhla"],
        "Myaing": ["Myaing"],
        "Myothit": ["Myothit"],
        "Natmauk": ["Matmauk"],
        "Ngape": ["Ngape"],
        "Pakokku": ["Pakokku"],
        "Pauk": ["Pauk"],
        "Pwintpyu": ["Pwintpyu"],
        "Salinn": ["Salinn"],
        "Saw": ["Saw"],
        "Saytoketaya": ["Saytoketaya"],
        "Seikpyu": ["Seikpyu"],
        "Sinpaungwe": ["Sinpaungwe"],
        "Taungtwinggyi": ["Taungtwinggyi"],
        "Thayet": ["Thayet"],
        "Yenanchaung": ["Yenanchaung", "Pinwa", "Nyaunghla"],
        "Yezakyo": ["Yezakyo"]
    },


    "Yangon": {
        "Yangon": ["Ahlone", "Bahan", "Botahtaung", "Coco Island", "Dagon", "Dagon Myothit (East)",
            "Dagon Myothit (Seikkan)", "Dagon Myothit (South)", "Dala", "Dawbon", "Hlaing", "Hlaingtharya (East)",
            "Hlaingtharya (West)", "Hlegu", "Hmawbi", "Htantabin", "Insein", "Kamayut", "Kawhmu", "Kayan",
            "Kungyangon", "Kyauktada", "Kyauktan", "Kyeemyindaing", "Lanmadaw", "Mayangone", "Mingalardon",
            "Mingalartaungnyunt", "Okkalapa (North)", "Okkalapa (South)", "Pabedan", "Pazundaung", "Sanchaung",
            "Seikgyikanaungto", "Shwe Pyi Thar", "Taikkyi", "Tamwe", "Tharkayta", "Thingangyun", "Twantay", "Yankin"]
    }


}